//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int Eid { get; set; }
        public string Ename { get; set; }
        public string ESalary { get; set; }
        public string Edepartment { get; set; }
        public string Eorganisation { get; set; }
    }
}
